title: Shikhar Shrestha
logo: /assets/shikharheadshot.png
description: Manager Product and Project @TysonFoods, Inc.
#show_downloads: true
theme: jekyll-theme-minimal

#Menu
navigation:
 - {title: "Launched Products", file: "/projects.html"}

#Social media
linkedin : www.linkedin.com/in/shikharstha




