title: Shikhar Shrestha
logo: /assets/shikharheadshot.png
description: Leading and building transformations in Software, Data Analytics, and Machine Learning | Agile Product Leader & Mentor | Certified Scrum Master, Lean Six Sigma Green Belt & Product Management | MBA candidate
#show_downloads: true
theme: jekyll-theme-minimal

#Menu
#navigation:
 #- {title: "Launched Products", file: "/projects.html"}
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up



#Social media
#linkedin : www.linkedin.com/in/shikharstha

#plugins:
  #- jekyll-feed
  #- jekyll-seo-tag
 # - jekyll-sitemap
 # - jekyll-paginate
 #- jekyll-spaceship




