title: Shikhar Shrestha
logo: /assets/shikharheadshot.png
description: Manager Product and Project @TysonFoods, Inc.
<style>
      .libutton {
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 7px;
        text-align: center;
        outline: none;
        text-decoration: none !important;
        color: #ffffff !important;
        width: 200px;
        height: 32px;
        border-radius: 16px;
        background-color: #0A66C2;
        font-family: "SF Pro Text", Helvetica, sans-serif;
      }
    </style>
<a class="libutton" href="www.linkedin.com/in/shikharstha">LinkedIn</a>
#show_downloads: true
theme: jekyll-theme-minimal
